### ISSUE TITLE
Upgrade to Gradle 5.0 with the Kotlin DSL

### ISSUE THREAD

**Issue by nbransby** [TeamHubApp/firebase-multiplatform#1]
This project will be a little more challenging as its a multiplatform project.

All the links from the previous issue apply, also this project depends on the last one (firebase-java) so before it will build you need to run the gradle task publishToMavenLocal on the firebase-java project.

It also needs updating to the latest multiplatform dsl, use this guide: 

https://blog.jetbrains.com/kotlin/2019/01/kotlin-1-3-20-released/

**Comment by sadevelopment** [comment]
Closed as part or PR https://github.com/TeamHubApp/firebase-multiplatform/pull/2
